name: docker-project

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nursery-web
    container_name: nursery-web-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env